language: c
sudo: false
addons:
  apt:
    sources:
    - avsm
    packages:
    - aspcud
    - ocaml
    - opam
    - ocaml-native-compilers
install: sh -ex ./Library/Ancillary/autoinstall bmake bsdowl opam
script: sh -ex ./Library/Ancillary/travisci
cache:
  directories:
  - ${HOME}/.local
  - ${HOME}/.opam
env:
  - TRAVIS_OCAML_VERSION=4.00.1 TRAVIS_ENABLE_PPX_REWRITER=no
  - TRAVIS_OCAML_VERSION=4.01.0 TRAVIS_ENABLE_PPX_REWRITER=no
  - TRAVIS_OCAML_VERSION=4.02.3 TRAVIS_ENABLE_PPX_REWRITER=yes
