### Makefile -- Monads

# Lemonade (https://github.com/michipili/lemonade)
# This file is part of Lemonade
#
# Copyright © 2013–2015 Michael Grünewald
#
# This file must be used under the terms of the CeCILL-B.
# This source file is licensed as described in the file COPYING, which
# you should have received as part of this distribution. The terms
# are also available at
# http://www.cecill.info/licences/Licence_CeCILL-B_V1-en.txt

LIBRARY=		lemonade

SRCS=			lemonade_Type.ml
SRCS+=			lemonade_Continuation.ml
SRCS+=			lemonade_Lazy.ml
SRCS+=			lemonade_List.ml
SRCS+=			lemonade_Maybe.ml
SRCS+=			lemonade_Reader.ml
SRCS+=			lemonade_Retry.ml
SRCS+=			lemonade_State.ml
SRCS+=			lemonade_Success.ml
SRCS+=			lemonade_Writer.ml

.include "ocaml.lib.mk"

### End of file `Makefile'
